apiVersion: apps/v1
kind: ReplicaSet
metadata:
  # Unique key of the ReplicaSet instance
  name: phpinfo-replicaset
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: simplilearn-phpinfo
  template:
    metadata:
      labels:
        app: simplilearn-phpinfo
    spec:
      containers:
      # Run the nginx image
      - name: nginx
        image: rkhyd79/simplilearn-phpinfo:latest
        command: 
          - "php"
        args:
          - "-f"
          - "index.php"
          - "-S"
          - "0.0.0.0:8080"
        - name: mysql-container
          image: mysql:latest
          env: 
            - name: MYSQL_ROOT_PASSWORD
              value: '1234'
